// angular/src/app/pages/create-post/create-post.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import {
    FormBuilder,
    FormControl,
    FormGroup,
    ReactiveFormsModule,
    Validators,
} from '@angular/forms'
import { surpriseMePrompts } from 'src/app/constant'
import { DallEService } from 'src/app/services/dall-e.service'
import { firstValueFrom } from 'rxjs'
import { PostService } from 'src/app/services/post.service'
import { Router } from '@angular/router'

@Component({
    selector: 'create-post',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule],
    templateUrl: './create-post.component.html',
    styleUrls: ['./create-post.component.scss'],
})
export class CreatePostComponent {
    generatingImg = false
    loading = false
    form!: FormGroup

    constructor(
        private fb: FormBuilder,
        private postService: PostService,
        private dallEService: DallEService,
        private router: Router
    ) {
        this.form = this.fb.group({
            name: this.fb.control('', Validators.required),
            prompt: this.fb.control('', Validators.required),
            photo: this.fb.control('', Validators.required),
        })
    }

    get name() {
        return this.form.get('name') as FormControl
    }

    get prompt() {
        return this.form.get('prompt') as FormControl
    }

    get photo() {
        return this.form.get('photo') as FormControl
    }

    async handleSubmit() {
        this.loading = true
        try {
            await firstValueFrom(this.postService.createPost(this.form.value))
            alert('Success')
            this.router.navigate(['home'])
        } catch (err) {
            alert(err)
        } finally {
            this.loading = false
        }
    }

    handleSurpriseMe() {
        const randomPrompt = this.getRandomPrompt(this.prompt.value)
        this.prompt.setValue(randomPrompt)
    }

    getRandomPrompt(prompt: string): string {
        const randomIndex = Math.floor(Math.random() * surpriseMePrompts.length)
        const randomPrompt = surpriseMePrompts[randomIndex]
        if (randomPrompt === prompt) return this.getRandomPrompt(prompt)
        return randomPrompt
    }

    async generateImage() {
        try {
            this.generatingImg = true
            const { photo } = await firstValueFrom(
                this.dallEService.createImage({
                    prompt: this.prompt.value,
                })
            )
            this.photo.setValue(`data:image/jpeg;base64,${photo}`)
        } catch (err) {
            alert(err)
        } finally {
            this.generatingImg = false
        }
    }
}

<div class="mx-auto max-w-2xl md:text-center">
    <h2 class="font-display text-3xl tracking-tight text-slate-900 sm:text-4xl">
        Create
    </h2>
    <p class="mt-4 text-lg tracking-tight text-slate-700">
        Generate an imaginative image through DALL-E AI and share it with the
        community
    </p>
</div>
<!-- onSubmit={handleSubmit} -->
<form class="mt-16 max-w-3xl" [formGroup]="form" (submit)="handleSubmit()">
    <div class="flex flex-col gap-5">
        <div>
            <div class="flex items-center gap-2 mb-2">
                <label
                    for="name"
                    [ngClass]="{
                        '!text-red-700': name.touched && name.invalid
                    }"
                    class="block text-sm font-medium text-gray-900"
                >
                    Your Name
                </label>
            </div>
            <input
                type="text"
                id="name"
                name="name"
                [ngClass]="{
                    '!border-red-500': name.touched && name.invalid
                }"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 outline-none block w-full p-3"
                placeholder="Ex., john doe"
                formControlName="name"
            />
        </div>

        <div>
            <div class="flex items-center gap-2 mb-2">
                <label
                    for="prompt"
                    [ngClass]="{
                        '!text-red-700': prompt.touched && prompt.invalid
                    }"
                    class="block text-sm font-medium text-gray-900"
                >
                    Prompt
                    <button
                        type="button"
                        (click)="handleSurpriseMe()"
                        class="font-semibold text-xs bg-gray-200 py-1 px-2 rounded-[5px] text-black"
                    >
                        Surprise me
                    </button>
                </label>
            </div>
            <input
                type="text"
                id="prompt"
                name="prompt"
                [ngClass]="{
                    '!border-red-500': prompt.touched && prompt.invalid
                }"
                class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-bluering-blue-500 outline-none block w-full p-3"
                placeholder="An Impressionist oil painting of sunflowers in a purple vase…"
                formControlName="prompt"
            />
        </div>

        <div
            class="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center"
        >
            <ng-container *ngIf="photo.value; else noPhoto">
                <img
                    src="{{ photo.value }}"
                    alt="{{ prompt.value }}"
                    class="w-full h-full object-contain"
                />
            </ng-container>
            <ng-template #noPhoto>
                <img
                    src="/assets/imgs/preview.png"
                    alt="preview"
                    class="w-9/12 h-9/12 object-contain opacity-40"
                />
            </ng-template>

            <div
                *ngIf="generatingImg"
                class="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg"
            >
                <div role="status">
                    <svg
                        aria-hidden="true"
                        class="inline w-10 h-10 mr-2 text-gray-200 animate-spin fill-green-500"
                        viewBox="0 0 100 101"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                    >
                        <path
                            d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                            fill="currentColor"
                        />
                        <path
                            d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                            fill="currentFill"
                        />
                    </svg>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-5 flex gap-5">
        <button
            (click)="generateImage()"
            [disabled]="!prompt"
            type="button"
            class="group inline-flex items-center justify-center rounded-lg py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 bg-green-600 text-white hover:text-green-100 hover:bg-green-500 active:bg-green-800 active:text-green-100 focus-visible:outline-green-600"
        >
            {{ generatingImg ? 'Generating...' : 'Generate' }}
        </button>
    </div>

    <div class="mt-10">
        <p class="mt-2 text-gray-500 text-[14px]">
            ** Once you have created the image you want, you can share it with
            others in the community **
        </p>
        <button
            type="submit"
            [disabled]="!form.valid"
            class="mt-3 group inline-flex items-center justify-center rounded-lg py-2 px-4 text-sm font-semibold focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 bg-blue-600 text-white hover:text-slate-100 hover:bg-blue-500 active:bg-blue-800 active:text-blue-100 focus-visible:outline-blue-600"
        >
            {{ loading ? 'Sharing...' : 'Share with the Community' }}
        </button>
    </div>
</form>

// react/src/page/CreatePost.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

import { preview } from '../assets';
import { getRandomPrompt } from '../utils';
import { FormField, Loader } from '../components';

const CreatePost = () => {
  const navigate = useNavigate();

  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });

  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });

  const handleSurpriseMe = () => {
    const randomPrompt = getRandomPrompt(form.prompt);
    setForm({ ...form, prompt: randomPrompt });
  };

  const generateImage = async () => {
    if (form.prompt) {
      try {
        setGeneratingImg(true);
        const response = await fetch(`${import.meta.env.VITE_API_URL}/v1/dalle`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            prompt: form.prompt,
          }),
        });

        const data = await response.json();
        setForm({ ...form, photo: `data:image/jpeg;base64,${data.photo}` });
      } catch (err) {
        alert(err);
      } finally {
        setGeneratingImg(false);
      }
    } else {
      alert('Please provide proper prompt');
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (form.prompt && form.photo) {
      setLoading(true);
      try {
        const response = await fetch(`${import.meta.env.VITE_API_URL}/v1/post`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ ...form }),
        });

        await response.json();
        alert('Success');
        navigate('/');
      } catch (err) {
        alert(err);
      } finally {
        setLoading(false);
      }
    } else {
      alert('Please generate an image with proper details');
    }
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">Create</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Generate an imaginative image through DALL-E AI and share it with the community</p>
      </div>

      <form className="mt-16 max-w-3xl" onSubmit={handleSubmit}>
        <div className="flex flex-col gap-5">
          <FormField
            labelName="Your Name"
            type="text"
            name="name"
            placeholder="Ex., john doe"
            value={form.name}
            handleChange={handleChange}
          />

          <FormField
            labelName="Prompt"
            type="text"
            name="prompt"
            placeholder="An Impressionist oil painting of sunflowers in a purple vase…"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />

          <div className="relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center">
            { form.photo ? (
              <img
                src={form.photo}
                alt={form.prompt}
                className="w-full h-full object-contain"
              />
            ) : (
              <img
                src={preview}
                alt="preview"
                className="w-9/12 h-9/12 object-contain opacity-40"
              />
            )}

            {generatingImg && (
              <div className="absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg">
                <Loader />
              </div>
            )}
          </div>
        </div>

        <div className="mt-5 flex gap-5">
          <button
            type="button"
            onClick={generateImage}
            className=" text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center"
          >
            {generatingImg ? 'Generating...' : 'Generate'}
          </button>
        </div>

        <div className="mt-10">
          <p className="mt-2 text-[#666e75] text-[14px]">** Once you have created the image you want, you can share it with others in the community **</p>
          <button
            type="submit"
            className="mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center"
          >
            {loading ? 'Sharing...' : 'Share with the Community'}
          </button>
        </div>
      </form>
    </section>
  );
};

export default CreatePost;
