// angular/src/app/pages/home/home.component.ts
import { CommonModule } from '@angular/common'
import { Component, OnInit } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { DebounceKeyupDirective } from 'src/app/directives/debounce-keyup.directive'
import { Post } from 'src/app/interfaces/post'
import { PostService } from 'src/app/services/post.service'
import { CardComponent } from './components/card/card.component'
import { FormFilterComponent } from './components/form-filter/form-filter.component'
import { FilterPostsPipe } from './pipes/filter-posts.pipe'

@Component({
    standalone: true,
    selector: 'home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.scss'],
    imports: [
        CommonModule,
        FormsModule,
        CardComponent,
        FormFilterComponent,
        DebounceKeyupDirective,
        FilterPostsPipe,
    ],
})
export class HomeComponent implements OnInit {
    posts: Post[] = []
    searchText = ''
    constructor(private postService: PostService) {}
    ngOnInit(): void {
        this.getPosts()
    }

    public handleDebouncedKeyUp(event: KeyboardEvent): void {
        this.searchText = (event.target as HTMLInputElement).value
    }

    getPosts() {
        this.postService.getPosts().subscribe((posts: any) => {
            this.posts = posts.data as Post[]
        })
    }
}

<main>
    <section class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div>
            <h1 class="font-extrabold text-[#222328] text-[32px]">
                The Community Showcase
            </h1>
            <p class="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
                Browse through a collection of imaginative and visually stunning
                images generated by DALL-E AI
            </p>
        </div>

        <div class="mt-16">
            <div>
                <div class="flex items-center gap-2 mb-2">
                    <label
                        for="text"
                        class="block text-sm font-medium text-gray-900"
                    >
                        Search posts
                    </label>
                </div>
                <input
                    type="text"
                    id="text"
                    name="text"
                    class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-[#6469ff] focus:border-[#6469ff] outline-none block w-full p-3"
                    placeholder="Search something..."
                    debounceKeyUp
                    (onEvent)="handleDebouncedKeyUp($event)"
                />
            </div>
        </div>

        <div class="mt-10">
            <h2
                *ngIf="searchText"
                class="font-medium text-[#666e75] text-xl mb-3"
            >
                Showing Resuls for
                <span class="text-[#222328]">{{ searchText }}</span
                >:
            </h2>
            <div
                class="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3"
            >
                <ng-container *ngIf="posts; else noData">
                    <home-card
                        class="rounded-xl group relative shadow-card hover:shadow-cardhover card"
                        *ngFor="let post of posts | filterPosts : searchText"
                        [post]="post"
                    ></home-card>
                </ng-container>
                <ng-template #noData>
                    <h2
                        className="mt-5 font-bold text-[#6469ff] text-xl uppercase"
                    >
                        No Posts Yet
                    </h2>
                </ng-template>
            </div>
        </div>
    </section>
</main>

// react/src/page/Home.jsx
import React, { useEffect, useState } from 'react';

import { Card, FormField, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post._id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};


const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setSearchText] = useState('');
  const [searchTimeout, setSearchTimeout] = useState(null);
  const [searchedResults, setSearchedResults] = useState(null);

  const fetchPosts = async () => {
    setLoading(true);

    try {
      const response = await fetch(`${import.meta.env.VITE_API_URL}/v1/post`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (response.ok) {
        const result = await response.json();
        setAllPosts(result.data.reverse());
      }
    } catch (err) {
      alert(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  const handleSearchChange = (e) => {
    clearTimeout(searchTimeout);
    setSearchText(e.target.value);

    setSearchTimeout(
      setTimeout(() => {
        const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
        setSearchedResults(searchResult);
      }, 500),
    );
  };

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className="mt-16">
        <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value={searchText}
          handleChange={handleSearchChange}
        />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
